# Generated by Django 5.2.4 on 2025-07-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view list of books'), ('can_create', 'Can add a book'), ('can_edit', 'Can edit attributes of a book'), ('can_delete', 'Can delete books')]},
        ),
    ]
